[project]
name = "foobar"
version = "0.0.1"
dependencies = [
]

[tool.setuptools.packages.find]
# All the following settings are optional:
where = ["."]  # ["."] by default
include = ["*"]  # ["*"] by default
exclude = ["foobar", "bar"]  # empty by default
namespaces = false  # true by default
